import type { Topic } from '../types'

export const TOPICS: Topic[] = [
  // Treasury
  {
    id: 'treasury-what-is',
    slug: 'what-is-dept-of-finance-canada',
    name: 'What is the Dept of Finance Canada?',
    category: 'treasury',
    emoji: '🏦',
    difficulty: 1,
    description: 'The government department that manages all of Canada\'s money',
  },
  {
    id: 'treasury-bonds',
    slug: 'government-of-canada-bonds',
    name: 'Government of Canada Bonds',
    category: 'treasury',
    emoji: '📜',
    difficulty: 1,
    description: 'IOUs the Canadian government sells to borrow money from investors',
  },
  {
    id: 'treasury-bills-notes',
    slug: 't-bills-bonds-real-return',
    name: 'T-Bills, Bonds & Real Return Bonds',
    category: 'treasury',
    emoji: '⏱️',
    difficulty: 2,
    description: 'Different types of Canadian government debt with different time horizons',
  },
  {
    id: 'treasury-boc-vs-finance',
    slug: 'bank-of-canada-vs-dept-of-finance',
    name: 'Bank of Canada vs Dept of Finance',
    category: 'treasury',
    emoji: '⚖️',
    difficulty: 2,
    description: 'Two powerful institutions that shape Canada\'s economy — what\'s the difference?',
  },
  {
    id: 'treasury-yield-curve',
    slug: 'yield-curve',
    name: 'The Yield Curve',
    category: 'treasury',
    emoji: '📈',
    difficulty: 3,
    description: 'The secret signal economists watch to predict recessions',
  },
  {
    id: 'treasury-national-debt',
    slug: 'federal-debt',
    name: 'Federal Debt',
    category: 'treasury',
    emoji: '💳',
    difficulty: 1,
    description: 'How much the Canadian government owes and why it matters to you',
  },
  {
    id: 'treasury-cash-mgmt',
    slug: 'cash-management',
    name: 'Cash Management',
    category: 'treasury',
    emoji: '💵',
    difficulty: 2,
    description: 'How the government makes sure it always has cash to pay its bills',
  },

  // Risk Management
  {
    id: 'risk-what-is',
    slug: 'what-is-financial-risk',
    name: 'What is Financial Risk?',
    category: 'risk',
    emoji: '🎲',
    difficulty: 1,
    description: 'The chance that something goes wrong with money or investments',
  },
  {
    id: 'risk-credit',
    slug: 'credit-risk',
    name: 'Credit Risk',
    category: 'risk',
    emoji: '🤝',
    difficulty: 1,
    description: 'What happens when someone you lent money to can\'t pay you back',
  },
  {
    id: 'risk-market',
    slug: 'market-risk',
    name: 'Market Risk',
    category: 'risk',
    emoji: '🌊',
    difficulty: 2,
    description: 'The risk that prices will move against you in unexpected ways',
  },
  {
    id: 'risk-liquidity',
    slug: 'liquidity-risk',
    name: 'Liquidity Risk',
    category: 'risk',
    emoji: '💧',
    difficulty: 2,
    description: 'The risk of not being able to get your money when you need it',
  },
  {
    id: 'risk-hedging',
    slug: 'hedging',
    name: 'Hedging',
    category: 'risk',
    emoji: '🛡️',
    difficulty: 2,
    description: 'Using financial instruments as insurance against bad outcomes',
  },
  {
    id: 'risk-var',
    slug: 'value-at-risk',
    name: 'Value at Risk (VaR)',
    category: 'risk',
    emoji: '📊',
    difficulty: 3,
    description: 'A mathematical way to measure how much you could lose on a bad day',
  },
  {
    id: 'risk-stress-test',
    slug: 'stress-testing',
    name: 'Stress Testing',
    category: 'risk',
    emoji: '💪',
    difficulty: 2,
    description: 'How regulators check if banks can survive a financial disaster',
  },
  {
    id: 'risk-foreign-exchange',
    slug: 'foreign-exchange',
    name: 'Foreign Exchange (FX)',
    category: 'risk',
    emoji: '🌐',
    difficulty: 1,
    description: 'How currencies are traded and why exchange rates move',
  },
  {
    id: 'risk-fx-swap',
    slug: 'fx-swap',
    name: 'FX Swaps',
    category: 'risk',
    emoji: '🔄',
    difficulty: 2,
    description: 'Simultaneously buying and selling currencies at different dates to manage FX exposure',
  },
  {
    id: 'risk-futures',
    slug: 'futures',
    name: 'Futures',
    category: 'risk',
    emoji: '📅',
    difficulty: 2,
    description: 'Contracts that lock in a price today for something you\'ll buy or sell in the future',
  },
  {
    id: 'risk-options',
    slug: 'options',
    name: 'Options',
    category: 'risk',
    emoji: '🎯',
    difficulty: 3,
    description: 'The right — but not obligation — to buy or sell an asset at a set price',
  },
  {
    id: 'risk-hedge-management',
    slug: 'hedge-management',
    name: 'Hedge Management',
    category: 'risk',
    emoji: '🗂️',
    difficulty: 3,
    description: 'Running a hedging program: strategy, instruments, effectiveness testing, and accounting',
  },

  // Accounting
  {
    id: 'accounting-what-is',
    slug: 'what-is-accounting',
    name: 'What is Accounting?',
    category: 'accounting',
    emoji: '📒',
    difficulty: 1,
    description: 'The language businesses use to keep track of money',
  },
  {
    id: 'accounting-balance-sheet',
    slug: 'balance-sheet',
    name: 'The Balance Sheet',
    category: 'accounting',
    emoji: '⚖️',
    difficulty: 1,
    description: 'A snapshot showing what a company owns and what it owes',
  },
  {
    id: 'accounting-income-statement',
    slug: 'income-statement',
    name: 'Income Statement',
    category: 'accounting',
    emoji: '💰',
    difficulty: 1,
    description: 'The report card that shows if a company made or lost money',
  },
  {
    id: 'accounting-cash-flow',
    slug: 'cash-flow-statement',
    name: 'Cash Flow Statement',
    category: 'accounting',
    emoji: '💸',
    difficulty: 2,
    description: 'Tracking the actual movement of cash in and out of a business',
  },
  {
    id: 'accounting-debits-credits',
    slug: 'debits-and-credits',
    name: 'Debits & Credits',
    category: 'accounting',
    emoji: '↔️',
    difficulty: 2,
    description: 'The two-sided system that keeps all accounting in balance',
  },
  {
    id: 'accounting-ale',
    slug: 'assets-liabilities-equity',
    name: 'Assets, Liabilities & Equity',
    category: 'accounting',
    emoji: '🧩',
    difficulty: 1,
    description: 'The three building blocks that every balance sheet is made of',
  },
]

export const TOPICS_BY_CATEGORY = {
  treasury: TOPICS.filter(t => t.category === 'treasury'),
  risk: TOPICS.filter(t => t.category === 'risk'),
  accounting: TOPICS.filter(t => t.category === 'accounting'),
}

export function getTopicById(id: string): Topic | undefined {
  return TOPICS.find(t => t.id === id)
}

export function getTopicBySlug(slug: string): Topic | undefined {
  return TOPICS.find(t => t.slug === slug)
}
